let donors = [
        {
                name: "Anu",
                        phone: "9876543210",
                                blood: "O+",
                                        locality: "Local Area",
                                                status: "available"
                                                    },
                                                        {
                                                                name: "Rahul",
                                                                        phone: "9876543211",
                                                                                blood: "A+",
                                                                                        locality: "Local Area",
                                                                                                status: "recent"
                                                                                                    },
                                                                                                        {
                                                                                                                name: "Meera",
                                                                                                                        phone: "9876543212",
                                                                                                                                blood: "B+",
                                                                                                                                        locality: "Local Area",
                                                                                                                                                status: "available"
                                                                                                                                                    }
                                                                                                                                                    ];


                                                                                                                                                    function showBloodGroup(group) {

                                                                                                                                                        let filtered = donors.filter(
                                                                                                                                                                donor => donor.blood === group
                                                                                                                                                                    );

                                                                                                                                                                        document.getElementById("groupTitle").innerText =
                                                                                                                                                                                group + " Blood Donors";

                                                                                                                                                                                    displayDonors(filtered);

                                                                                                                                                                                        document
                                                                                                                                                                                                .getElementById("donors")
                                                                                                                                                                                                        .scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                        }


                                                                                                                                                                                                        function displayDonors(list) {

                                                                                                                                                                                                            const donorList =
                                                                                                                                                                                                                    document.getElementById("donorList");

                                                                                                                                                                                                                        donorList.innerHTML = "";

                                                                                                                                                                                                                            if (list.length === 0) {

                                                                                                                                                                                                                                    donorList.innerHTML = `
                                                                                                                                                                                                                                                <div class="donor-card">
                                                                                                                                                                                                                                                                <h3>No donors found</h3>
                                                                                                                                                                                                                                                                                <p>There are currently no registered donors
                                                                                                                                                                                                                                                                                                in this blood group.</p>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                    `;

                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                    list.forEach(donor => {

                                                                                                                                                                                                                                                                                                                                            let statusText;
                                                                                                                                                                                                                                                                                                                                                    let statusClass;

                                                                                                                                                                                                                                                                                                                                                            if (donor.status === "available") {
                                                                                                                                                                                                                                                                                                                                                                        statusText = "● Available";
                                                                                                                                                                                                                                                                                                                                                                                    statusClass = "available";
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    else if (donor.status === "recent") {
                                                                                                                                                                                                                                                                                                                                                                                                                statusText = "● Recently Donated";
                                                                                                                                                                                                                                                                                                                                                                                                                            statusClass = "recent";
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        statusText = "● Not Available";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    statusClass = "not-available";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    donorList.innerHTML += `

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="donor-card">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>${donor.name}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="blood-badge">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ${donor.blood}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>📍 ${donor.locality}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="status ${statusClass}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${statusText}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onclick="contactDonor('${donor.phone}')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Contact Donor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function contactDonor(phone) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.location.href = "tel:" + phone;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function showDonors() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .getElementById("donors")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function showRegistration() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .getElementById("register")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .getElementById("donorForm")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .addEventListener("submit", function(event) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                event.preventDefault();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const newDonor = {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: document.getElementById("name").value,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                phone: document.getElementById("phone").value,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            blood: document.getElementById("bloodGroup").value,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        locality: document.getElementById("locality").value,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: document.getElementById("status").value

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    donors.push(newDonor);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Thank you! You have been registered as a donor."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.reset();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateStats();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        displayDonors(donors);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function updateStats() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("totalDonors").innerText =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        donors.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("availableDonors").innerText =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    donors.filter(d => d.status === "available").length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("recentDonors").innerText =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                donors.filter(d => d.status === "recent").length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateStats();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                displayDonors(donors);
